# note: 该配置文件仅用于开发环境
server:
  context-path: /business-manage
  port: 8070
  undertow:
    io-threads: 2
    worker-threads: 5
    accesslog:
      enabled: true
      pattern: "%h %l %u %{time,[dd/MMM/yyyy:HH:mm:ss.SSS Z]} \"%r\" %s %b \"%{i,Referer}\" \"%{i,User-Agent}\""
      dir: "/var/business/access-logs/manage"

spring:
  datasource:
    url : "jdbc:mysql://192.168.18.107:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username : niiwoowrite
    password : niiwoo@write@123
    driverClassName : com.mysql.jdbc.Driver

sharding:
  data-sources:
    stage:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: "jdbc:mysql://192.168.18.107:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
        username: niiwoowrite
        password: niiwoo@write@123
      slaves:
        - driver-class-name: com.mysql.jdbc.Driver
          url: "jdbc:mysql://192.168.18.108:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
          username: niiwooread
          password: niiwoo@read@123
        - driver-class-name: com.mysql.jdbc.Driver
          url: "jdbc:mysql://192.168.18.108:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
          username: niiwooread
          password: niiwoo@read@123
  default-data-source-name: stage
  rule-config-location: classpath:shardingjdbc.yml

mybatis:
  mapper-locations: classpath*:com/backend/business/dao/mapping/*.xml