# note: 该配置文件用于与环境无关的公共配置
spring:
  application:
    name: "business-manage"
  profiles:
    active: @build.profile.id@

# log file
logging:
  context-name: ${spring.application.name}
  path: "/app1/logs/business/${spring.application.name}"
  rolling-policy:
    max-file-size: 200MB
    max-history: 500
    total-size-cap: 100GB
  stash:
    destination: 192.168.18.105:2013
    type: "business-manage-log-${spring.profiles.active}"