# note: 该配置文件仅用于开发环境
server:
  context-path: /business-manager
  port: 8070
  undertow:
    io-threads: 2
    worker-threads: 5
    accesslog:
      enabled: true
      pattern: "%h %l %u %{time,[dd/MMM/yyyy:HH:mm:ss.SSS Z]} \"%r\" %s %b \"%{i,Referer}\" \"%{i,User-Agent}\""
      dir: "/var/business/access-logs/manage"

spring:
  redis:
    host: 192.168.18.103
    port: 6379
    password: ace@redis99
    database: 9
    timeout: 10000
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: 2000
  rabbitmq:
    host: 192.168.18.108
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
    template:
      mandatory: true
    publisher-confirms: true
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

sharding:
  data-sources:
    stage:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: "jdbc:mysql://192.168.18.107:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
        username: niiwoowrite
        password: niiwoo@write@123
      slaves:
        - driver-class-name: com.mysql.jdbc.Driver
          url: "jdbc:mysql://192.168.18.108:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
          username: niiwooread
          password: niiwoo@read@123
        - driver-class-name: com.mysql.jdbc.Driver
          url: "jdbc:mysql://192.168.18.108:3388/activity_stage?useUnicode=true&characterEncoding=utf-8&useSSL=false"
          username: niiwooread
          password: niiwoo@read@123
  default-data-source-name: stage
  rule-config-location: classpath:shardingjdbc.yml

mybatis:
  mapper-locations: classpath*:com/backend/business/dao/mapping/**/*.xml

shiro:
  enabled: true
  render-page-mode: false
  session:
    prefix: "businesssid:"
    time-out-hours: 2
  hashed-credential:
    hash-algorith-name: md5
    hash-iterations: 3
  cache:
    authorization-caching-enabled: true
    authenticationCachePrefix: "shield-web-ac:" #shield-web.shiro-authentication
    authorizationCachePrefix: "shield-web-az:"  #shield-web.shiro-authorization